### ISSUE TITLE
Channel error

### ISSUE THREAD

**Issue by lordm121** [Valks-Bots/partner-bot#46]
Hello when I host bot for 24h after 1day or 2 days all setups rest like channel and description 
Can you help me how to fix it I host on heroku

**Comment by valkyrienyanko** [comment]
This happens on the freemium version of Heroku. You have 3 options that I can think of.

1. Host the bot on your local Windows machine instead. (The best option imo)
2. Buy Heroku Premium
3. Learn [Heroku Postgres](https://www.heroku.com/postgres) (Depends on what you want, look at the free plan and how much they are limiting you, I never looked into this myself just because it was such a big rabbit hole)
